# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cdd7ae18c936b0cec04e1ef293252201f3209be83909a03c421d1099a8554dbb29abebd342945a3a8ddb4a8935c83e34fda48244c65d7a602f7180f254cfe5

test:
  secret_key_base: 1adee07a5a70b6629a25bd2c6f5aa254da8d0a39e8ea03f0b0d4c0270836d8db0197cc36d3c3c3fe2708b46371846d0e448eccf64ea22e90dc2baced7502a67a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
